- name: Prepare public EC2 for UCView installation
  delegate_to: "{{ public_ip }}" # all tasks in this block will run on the public EC2 instance
  become: true # all tasks in this block will run with sudo (like root)
  remote_user: "{{ ssh_user }}" 
  vars:
    ansible_ssh_private_key_file: "{{ local_key_path }}"
    ansible_host_key_checking: False # disables the security prompt (as discussed)
  block:

    - name: Ensure /home/ubuntu has correct permissions
      ansible.builtin.file:
        path: /home/ubuntu
        mode: '0700'
        state: directory

    - name: Set permissions for remote SSH key
      ansible.builtin.file:
        path: "{{ remote_key_path }}"
        mode: '0600' 
        state: file 

    - name: Add Nginx GPG key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        keyring: /usr/share/keyrings/nginx-archive-keyring.gpg
        state: present

    - name: Add Nginx APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"
        state: present
        filename: nginx

    - name: Add UCView GPG key
      ansible.builtin.apt_key:
        url: https://packages.ucview.com/public.gpg
        keyring: /usr/share/keyrings/ucview-archive-keyring.gpg
        state: present

    - name: Add UCView APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/ucview-archive-keyring.gpg] http://packages.ucview.com/dists/{{ ansible_distribution_release }} ./"
        state: present
        filename: ucview

    - name: Add Google Chrome GPG key 
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub 
        keyring: /usr/share/keyrings/google-chrome.gpg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add Google Chrome APT repository (for 'NO_PUBKEY 32EE5355A6BC6E42' error)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
        filename: google-chrome
      when: ansible_distribution == 'Ubuntu'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install UCView Appliance and Nginx packages
      ansible.builtin.apt:
        name:
          - ucview-appliance8
          - ucview-nginx8
        state: present
        update_cache: yes
        force_apt_get: yes # Force apt-get usage, sometimes needed for noninteractive scenarios

    - name: Verify UCView installation with curl
      ansible.builtin.shell: curl -I http://localhost/user/server_sign_up || echo "installation failed"
      become: true
      register: ucview_check

    - name: Show UCView curl response
      debug:
        var: ucview_check.stdout_lines

    - name: Create local package directory
      ansible.builtin.file:
        path: /home/ubuntu/{{ package_dir }}
        state: directory
        mode: '0755'

    - name: Copy downloaded .deb packages to local directory
      ansible.builtin.shell: |
        cp /var/cache/apt/archives/*.deb /home/ubuntu/{{ package_dir }}/ 2>/dev/null || echo "no debs"
      args:
        chdir: /home/ubuntu 

    - name: Generate Packages.gz and Packages files for local repo
      ansible.builtin.shell: |
        cd /home/ubuntu/{{ package_dir }}
        dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
        dpkg-scanpackages . /dev/null > Packages
      args:
        chdir: /home/ubuntu/{{ package_dir }}

    - name: Create tar archive of local package directory
      ansible.builtin.archive:
        path: /home/ubuntu/{{ package_dir }}
        dest: /home/ubuntu/{{ tar_name }}
        format: gz
   
    - name: Add private EC2 host key to known_hosts on public EC2
      shell: |
        ssh-keyscan -H {{ private_ip }} >> /home/ubuntu/.ssh/known_hosts
      delegate_to: "{{ hostvars['public-ec2'].ansible_host }}"
      remote_user: ubuntu

- name: Copy tar archive to private EC2 using scp from public EC2
  ansible.builtin.shell: |
    scp -o StrictHostKeyChecking=no -i {{ remote_key_path }} /home/ubuntu/{{ tar_name }} {{ ssh_user }}@{{ private_ip }}:/home/{{ ssh_user }}/
  delegate_to: "{{ hostvars['public-ec2'].ansible_host }}"
  become: true
  remote_user: "{{ ssh_user }}"