---
- name: Include vars
  include_vars: "../vars/main.yml"

- name: Load dynamic vars from inventory
  set_fact:
    public_ip: "{{ hostvars['public-ec2'].ansible_host }}"
    private_ip: "{{ hostvars['private-ec2'].ansible_host }}"

- name: Wait for SSH on public EC2
  wait_for:
    host: "{{ public_ip }}"
    port: 22
    delay: 5
    timeout: 180
    state: started
  delegate_to: localhost

- name: Copy SSH key to public machine
  copy:
    src: "{{ local_key_path }}"
    dest: "{{ remote_key_path }}"
    mode: '0600'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
  delegate_to: "{{ public_ip }}"
  become: true
  remote_user: "{{ ssh_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ local_key_path }}"
    ansible_host_key_checking: False 

- name: Show details of copied key
  debug:
    msg: |
      ✅ Copied SSH key successfully:
      - From local path: {{ local_key_path }}
      - To remote host: {{ public_ip }}
      - Remote path: {{ remote_key_path }}
      - As user: {{ ssh_user }}
  delegate_to: localhost


- name: Install UCView on public and package it
  import_tasks: install_ucview_public.yml

- name: Install UCView on private machine
  import_tasks: install_ucview_private.yml

- name: Done
  debug:
    msg: "UCView installation flow completed."
