pipeline {
    agent any

    environment {
        TF_VAR_FILE = credentials('terraform-vars-file')
    }

    stages {
        stage('Terraform Init + Apply') {
            steps {
                dir('terraform') {
                    withCredentials([file(credentialsId: 'terraform-vars-file', variable: 'TFVARS_FILE')]) {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve -var-file=$TFVARS_FILE'
                    }
                }
            }
        }

        stage('Run Ansible') {
            steps {
                dir('ansible') {
                    sh '/home/ubuntu/.local/bin/ansible-playbook -i inventory.ini playbook.yml'
                }
            }
        }
    }
}
